# Generated by Django 5.2.4 on 2025-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
            ],
        ),
    ]
