# Generated by Django 5.2.4 on 2025-07-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieuser',
            old_name='borrower',
            new_name='username',
        ),
    ]
