# Generated by Django 5.2.4 on 2025-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_borrower_movieuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
